bot_token: <token>
env: <one from>(debug, dev, prod)
db: <postgresql_host>
time_to_ping: <time to ms>  (default 5000)
rabbitMQ:
  host: <mq_host>
  topic:
    fromServerName: <topic_name> 
    fromWorkerName: <topic_name>