bot_token: <token>
env: <one from>(debug, dev, prod)
db: <postgresql_host> #for local test ?sslmode=disable
time_to_ping: <time to ms>  #(default 60000 / 1 minutes )
rabbitMQ:
  host: <mq_host>
  topic:
    fromServerName: <topic_name> 
    fromWorkerName: <topic_name>